version: "3.9"
services:
  api:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - llm
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: kirtisrivastava
      POSTGRES_PASSWORD: 17Feb2025@123
      POSTGRES_DB: luminalib
    ports:
      - "5432:5432"
  llm:
    image: ollama/llama3:latest
    ports:
      - "11434:11434"

FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

